node {
  name = "emqx@127.0.0.1"
}

listeners.tcp.default {
  bind = "0.0.0.0:${MQTT_PORT}"
}

dashboard.listeners.http.bind = "${CONTROL_INTERFACE}:18083"

durable_sessions.enable = false
log.console.level = warning
